-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1bbBc0vQlCEzKW3J
Y9Yx8qBUP/sRyDDGO1MlW8ly8segCgYIKoZIzj0DAQehRANCAARxq8QFt/ihfWMq
OdGJCUJkwElalUzI5Evw28MfZDbviFbGCBBGWz0dLDbtggDY8lPWRtQ4sKDwfJUn
65XCGKyO
-----END PRIVATE KEY-----